// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'Cart': string;
  'Logo': string;
  'Menu': string;
  'container': string;
}
export const cssExports: CssExports;
export default cssExports;
